### ISSUE TITLE
The expansion limit for "air" in HB too low

### ISSUE THREAD

**Issue by sonercandas** [open-modex/models#1]
Dear all, a problem with the current input data that leads to infeasibility caught my attention:

The expansion limit for wind in HB: 129.35 (MW)
The already installed capacity for wind in HB in 2016: 162.49 (MW)

This most likely is caused by the uncertainties in the software we used for the potential limits, which are more pronounced for city federal-states such as Bremen in this case.

One solution would be of course just setting the expansion limit = installed capacity in the input file.

**Comment by StefanieBuchholz** [comment]
Dear all, 

I understood the expansion limit as a limit to how much the current installation can be expanded. Consequently, the maximum that you Soner, talks about is to me 129.35+162.49 - which limits the total capacity. In that case there is no infeasibility problem. However, I may be wrong in my interpretation of the expansion limit, so it would be nice if someone can clarify :) 

best regards, 

Stefanie

**Comment by chrwm** [comment]
Dear all, I understood the expansion limits as theoretical maximum total expansion limits. Hence I would interpret the expansion limit as an upper limit itself as Soner did.
@sonercandas is this the way the data should be interpreted or rather like Stefanie suggested?

**Comment by sonercandas** [comment]
> Dear all, I understood the expansion limits as theoretical maximum total expansion limits. Hence I would interpret the expansion limit as an upper limit itself as Soner did.
> @sonercandas is this the way the data should be interpreted or rather like Stefanie suggested?

This is true, the values give the total limits.

**Comment by StefanieBuchholz** [comment]
Alright, sorry for any confusion I caused. I will return to my code and correct my mistake :) 
I am fine by setting the expansion limit = installed capacity in the specific HB-wind case as Soner suggest to avoid the infeasibility. But as a general solution, I would suggest to correct the input data itself if it needs update anyway.

**Comment by chrwm** [comment]
> But as a general solution, I would suggest to correct the input data itself if it needs update anyway.

**Yes I will incorporate it and set the expansion limit (HB, 'air') = 162.49MW**
