### ISSUE TITLE
Storage Efficiencies: E2P Ratio or conversion losses?

### ISSUE THREAD

**Issue by khainsch** [open-modex/models#11]
We have a question with regard to the Parameters "Input Ratio" and "Output Ratio" of the storage technologies: 
- What unit are the values given here? Or better said, what does the number represent?

We were thinking about it and couldn't come to a satisfying answer, also we were wondering if efficiency losses (of storages) are modeled somewhere in the data set and we were just not able to find it.

**Comment by sonercandas** [comment]
I interpreted these as the charging and discharging efficiencies.

**Comment by khainsch** [comment]
**@sonercandas You are right, something wrong on our side. Will check the data conversion again, thanks anyway.
Issue closed**
