### ISSUE TITLE
Expansion limit for PV

### ISSUE THREAD

**Issue by StefanieBuchholz** [open-modex/models#12]
Just a clarification question: 

The parameter name 'expansion limit' is provided for a specific technology, for a specific region in a specific year. However, for photovoltaics it has the technology type 'unknown' rather than either 'rooftop' or 'utility' as otherwise used to define a specific PV technology. My guess is, that it is because you want this limit to be a common limit for all technologies concerning photovoltaics in the specified region. Is this a correct interpretation? (probably @chrwm (sorry!)) 
If yes, then as far as I see this is the only limit which covers multiple technologies - however I can have overlooked something.

**Comment by chrwm** [comment]
> My guess is, that it is because you want this limit to be a common limit for all technologies concerning photovoltaics in the specified region. Is this a correct interpretation?

Yes, this is the correct interpretation.

> If yes, then as far as I see this is the only limit which covers multiple technologies

- for "expansion limit" it is correct

But

- the "natural domestic limit" is existent for the fuels "lignite", "biomass", "waste" and hence is defined for all technologies that run with the respective fuel
