### ISSUE TITLE
Infeasibilities in data (ID18)

### ISSUE THREAD

**Issue by StefanieBuchholz** [open-modex/models#13]
**Issue in which we can state if we encounter any infeasibilities.** 

Balmorel turns infeasible when I try to solve the demand profile in ID18 for 2016. I believe the infeasibility arise due to the demand not being possible to satisfy with the installed capacities. These infesibilities do not occur if I use the demand profile from ID15 (for 2016), wherefore I believe the problem came with the ID16, where demands were updated. At the moment, I have not solved the model for 2030 and 2050 (ID18 data) so I do not (yet) know if these are infeasible too.

**Comment by chrwm** [comment]
In ID18 the demands are slightly higher compared to ID15. 
I propose to see if the updated transmission efficiency in ID19 is a sufficient change to solve the infeasibility.

**Comment by StefanieBuchholz** [comment]
Update from Balmorel: With ID15 demand for 2016 and ID18 demand for 2030 and 2050 Balmorel solves the problem without any infeasibilities.

**Comment by chrwm** [comment]
Thanks for the update. The new transmission efficiency will be 97% . Maybe this resolves the issue.

**Comment by StefanieBuchholz** [comment]
From the side of Balmorel: With the changes in ID19, we no longer have infeasibilities in the demand of 2016.

**Comment by chrwm** [comment]
Can the issue be closed?

**Comment by StefanieBuchholz** [comment]
Yes :) 
**I just closed it, and if any new infeasibilities arise I guess we open up a new issue.**
