### ISSUE TITLE
Result collection

### ISSUE THREAD

**Issue by StefanieBuchholz** [open-modex/models#15]
Dear all, 

Since Jonas made the location where we can put in our results..:
https://next.rl-institut.de/apps/files/?dir=/open_MODEX/01_WG_content/08_RC_Result_Comparison/01_Results&fileid=541551
..I guess it would be nice to have kind of an ongoing issue here, in which we can update Jonas and each other when and which results we upload. 

**Balmorel:** 
**17/03/2021:** Upload of results for 2016 (ID19 with the changes suggested my Soner/Christoph in Issue 'ID19 update #14')
https://next.rl-institut.de/apps/files/?dir=/open_MODEX/01_WG_content/08_RC_Result_Comparison/01_Results/Balmorel/ID19/2016%20Results&fileid=1024607  
Upload of results for 2030 (ID19 with the changes suggested my Soner/Christoph in Issue 'ID19 update #14')
https://next.rl-institut.de/apps/files/?dir=/open_MODEX/01_WG_content/08_RC_Result_Comparison/01_Results/Balmorel/ID19/2030%20Results&fileid=1024607 

**Urbs:**

**GENESYS-MOD:**

**GENESYS2:**

**oemof:**

**Comment by srhbrnds** [comment]
thx, good idea :)

**Comment by henhuy** [comment]
Tomorrow, I will show how this data can be uploaded easily via oedatamodel_api directly to OEP. From there it can be imported/analyzed with our results dashboard.

**Comment by henhuy** [comment]
Uploaded my Balmorel-Upload-Progress to:
https://next.rl-institut.de/apps/files/?dir=/open_MODEX/01_WG_content/08_RC_Result_Comparison/01_Results/Example_Balmorel_upload_steps&fileid=1026176
Added a Steps.md where all changes are logged. Hope this helps!

**Comment by jonasVano** [comment]
I think this issue moved ! 

https://github.com/open-modex/result_comparison/issues/4

But thanks Stefanie and sorry nobody put in their IDs. Have to check those issues more regularly...

**Comment by jonasVano** [comment]
I think we probably can close the issue then?

**Comment by henhuy** [comment]
You are right!

**Comment by StefanieBuchholz** [comment]
@jonasVano, @henhuy No problem at all :) 
This issue was actually meant for keeping track on what data ID our results covers. So e.g. I just uploaded results of data ID31, but before then the results of Balmorel was from data ID19 or something like that. I guess this is kind of important to know when we compare different frameworks in the dashboard because maybe we are comparing frameworks that are made from different data versions. Eventually, all framework will cover the same data upload but until then in open-modex/result_comparison#4 we maybe could specify also what data ID our upload covers :)

**Comment by henhuy** [comment]
Good idea!
Maybe data version should be present in upload data as well? 
Maybe in scenario source or comment field?
