### ISSUE TITLE
Limit for geothermal potential?

### ISSUE THREAD

**Issue by sonercandas** [open-modex/models#16]
Hi, my 2050 model covers around 80% of the electricity demand from geothermal power plants. This seems to be way off...
However, this result makes sense as it is modelled right now in a quite attractive way: As soon as the plant is build, it just runs at full load since there are no variable/fuel costs attached.

So I would have two questions:

- Do you get a similar result? (If not, perhaps I made a mistake here somehow, with the investment costs or so)
- If you get a similar result, would it be thinkable to introduce a limit for the geothermal heat supply? (as far as I know, there is no such limit right now)
 
Please let me know if I am missing something!

Best,
Soner

**Comment by StefanieBuchholz** [comment]
Hi Soner, 

From the Balmorel side already in 2030 the geothermal source becomes quite dominant but especially, as you say, in 2050 it is almost only geothermal - so I see similar results! 

Best 
Stefanie

**Comment by sonercandas** [comment]
Yes, in 2030 i get around 40% geothermal too...

**Comment by chrwm** [comment]
A expansion limit for geothermal is introduced in ID31.
