### ISSUE TITLE
Missing Parameters for Technologies

### ISSUE THREAD

**Issue by khainsch** [open-modex/models#20]
There are a couple (at least two) technologies where the parameters "Fuel Costs" and "Emission Factor" are missing:
1. Technology: chp, Technology_type: gas, input_energy_vector: light oil 
2. Technology: generator, Technology_type: combustion engine, input_energy_vector: natural gas 

I can't say right now if there are any other technologies affected but those are the main reasons, why we have no consistent results for the current base case in 2030 and 2050, since the resulting exceptional low cost make them way more preferable compared to the others.

**Comment by chrwm** [comment]
I will look into it

**Comment by chrwm** [comment]
I updated the corresponding values in ID28. 
Now all fossil-based energy transformation technologies have a value for the parameter "emission factor", except for nuclear and  biomass and biogas. The latter are assumed to be carbon neutral.
The parameter "fuel costs" is assigned for all fossil-based energy transformation technologies, including biomass and biogas, but not for energy transformation processes from waste. 
All renewables energy transformation technologies based on wind, solar, hydro or geothermal have neither "emission factor" or "fuel costs". The same goes for the storage and transmission technologies.
