### ISSUE TITLE
Hydro timeseries Bayern

### ISSUE THREAD

**Issue by sonercandas** [open-modex/models#21]
Hi all,

If I am not mistaken the BY capacity factor timeseries for hydro run-of_river results in around 18 full load hours for each of the years 2016, 2030, 2050. Is this really conceivable?

**Comment by chrwm** [comment]
Hi Soner, I will look into it.

**Comment by chrwm** [comment]
Hello Soner, there was an error in the script for calculating the full load hours. The quotient of generation and installed capacity of hydropower was formed from two lists, which were not correctly sorted by federal state. That is where the error came from. Thank you for discovering this. It will be corrected in the next ID.

**Comment by chrwm** [comment]
It is fixed in ID31.
