### ISSUE TITLE
RES expansion targets 2030, 2050 

### ISSUE THREAD

**Issue by StefanieBuchholz** [open-modex/models#4]
Dear all, 

Renewable share is still missing in the input data it seems, or did anyone manage to see it? 
Additionally, it is the total summed installed (renewable) capacity  that we put a minimum limit on? or is it the generation from these renewable technologies? Personally, I believe the genration makes the most sense, but from the name it seems to be the capacity - and in the end, the two are linked.  

Lastly, I earlier talked to Christoph about the definition of renewables, and we agreed that the following would go into that category: Wind, Solar, Hydro, Geothermal, Biomass, and Biogas. If this is different from your definition, we should re-iterate :) 

best regards, 

Stefanie

**Comment by chrwm** [comment]
Hi Stefanie,
you're right they are still missing. I wanted to avoid a series of small changes per upload and rather go for a big update.
With the increasing number of issues, this might be unavoidable, so I will upload the ID15, including the renewable share, today.

> or is it the generation from these renewable technologies?

Yes, the target is meant as a share of electricity generation, also according to the intention of the law from which the target originates.

**Comment by StefanieBuchholz** [comment]
Hi :) 

With the answer above, I can prepare the code witout having the true data, so for me it is fine if you wanted to wait with the update! Thanks for the clarification!

best Stefanie
