### ISSUE TITLE
Investments in Transmission lines

### ISSUE THREAD

**Issue by StefanieBuchholz** [open-modex/models#5]
Hi all, 

As far as I see, currently distances are provided for the transmission lines that in 2016 has existing capacities. Do we assume that only these lines can be expanded in later years and that no new lines can be installed?

We earlier talked about which lines one can invest in, and I am not sure if we reached a conclusion. I think we said that we can invest in any line that connects a region to its neighboring region. E.g. although there is no existing line in 2016 between SN and ST, this could be installed in later years. On the other hand a line between SN and NI cannot be installed. I am not completely sure whether this was the conclusion or if I remember wrong. 

Anyway, my point being, that if we can invest in lines that do not have existing capacity in 2016 (e.g. a line SN-ST), then we need distances for these potential lines as well, otherwise we have no investments costs for them. 

Additionally: I have assumed that any generation technologies can be installed in any region (except for the offshore wind technologies which are limited to Baltic and North). Is this fine? 

best regards, 

Stefanie

**Comment by chrwm** [comment]
> Do we assume that only these lines can be expanded in later years and that no new lines can be installed?

**We assume that new transmission lines can be built between neighbouring federal states, even though they're not yet connected in 2016. This is the case for 
['BB','NI']
['SN','ST']
['SN','BY']
['NI','TH']
['BY','TH']
The distances for these connections will also be added in ID15.**

> On the other hand a line between SN and NI cannot be installed. 

This is correct regarding our current assumption above. The model will need to expand capacity to its neighbouring states first and from there build more to NI.

> Additionally: I have assumed that any generation technologies can be installed in any region (except for the offshore wind technologies which are limited to Baltic and North). Is this fine?

We haven't discussed this yet. Maybe we open another issue on that?
