### ISSUE TITLE
Implement a parameter for the capacity upper limit to restrict investments

### ISSUE THREAD

**Issue by chrwm** [open-modex/models#8]
We want to implement an upper limit on the theoretical maximum installed capacity per technology per year to restrict investments into technologies

**Comment by jonasVano** [comment]
is this for the pasthway approach? Because in the Pathway sceanario I can only set limits for the base years. For the base scenario I can set limits, no Problem

**Comment by chrwm** [comment]
A capacity upper limit parameter was introduced in ID19 for the years 2030 & 2050.
